import MenuBar from "@/components/MenuBar";
import "../app/global.css";

export const metadata = {
  title: "Vaccination Service",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>
        <MenuBar />
        <div className="mt-20">{children}</div>
      </body>
    </html>
  );
}
